@@OBJECTS/CONTRAINTS/FOREINGI_KEY/besoin
@@OBJECTS/CONTRAINTS/FOREINGI_KEY/candidature
@@OBJECTS/CONTRAINTS/FOREINGI_KEY/liste_secteur
@@OBJECTS/CONTRAINTS/FOREINGI_KEY/publication
@@OBJECTS/CONTRAINTS/FOREINGI_KEY/recommendations