ALTER TABLE APPLICANT
ADD
CONSTRAINT fk_locations FOREIGN KEY (location_id)
REFERENCES LOCATIONS(location_id);

ALTER TABLE OFFERS
ADD 
CONSTRAINT fk_job_id FOREIGN KEY (job_id)
REFERENCES jobs(job_id)

ALTER TABLE OFFERS
ADD
CONSTRAINT fk_Offrer FOREIGN KEY (offrer_id)
REFERENCES OFFRER(offrer_id)

ALTER TABLE OFFERS
ADD
CONSTRAINT fk_offrer FOREIGN KEY (applicant_id)
REFERENCES APPLICANT

-- By toko --