PROMPT Creating table APPLICANTS
CREATE TABLE APPLICANTS(
    applicant_id integer generated by default on null as identity,
    first_name VARCHAR(70 CHAR) not null,
    last_name VARCHAR(70 CHAR)not null,
    phone_number NUMBER(1,38),
    email VARCHAR(80 CHAR)NOT NULL,
    password VARCHAR(80 CHAR)NOT NULL,
    location_id integer NOT NULL,
    status VARCHAR(15 CHAR) NOT NULL,
    compte_premium varchar(10 char) not null
    );
    PROMPT Creating table PROPOSER
CREATE TABLE PROPOSERS(
    proposer_id integer generated by default on null as identity,
    first_name VARCHAR(70 CHAR) not null,
    last_name VARCHAR(70 CHAR)not null,
    phone_number NUMBER(1,38),
    email VARCHAR(80 CHAR)NOT NULL,
    password VARCHAR(80 CHAR)NOT NULL,
    compte_premium varchar(10 char) not null
    );
    PROMPT Creating table JOB_HISTORIES
    CREATE TABLE  JOB_HISTORIES(
    job_history_id  integer generated by default on null as identity,
    start_date timestamp not null,
    end_date timestamp ,
    user_id  integer not null,
    offer_id integer not null
);
PROMPT Creating table JOBS
CREATE TABLE JOBS (
job_id integer generated by default on null as identity,
job_title VARCHAR(70 CHAR) not null
);

PROMPT Creating table OFFERS
CREATE TABLE OFFERS(
    offer_id integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    publication_time TIMESTAMP,
    proposer_id integer,
    applicant_id integer,
    location_id integer,
    job_id VARCHAR(50 char),
    statut varchar(10 char) not null
);
PROMPT Creating table LOCATIONS
CREATE TABLE LOCATIONS
(
    location_id integer NOT NULL,
    city varchar(70) NOT NULL
);
