PROMPT Creating table APPLICANTS
CREATE TABLE APPLICANTS(
    applicant_id interger generated by default on null as identity,
    first_name VARCHAR(70 CHAR) not null,
    last_name VARCHAR(70 CHAR)not null,
    phone_number NUMBER(),
    email VARCHAR(80 CHAR)NOT NULL,
    password VARCHAR(80 CHAR)NOT NULL,
    location_id interger NOT NULL,
    status VARCHAR(15 CHAR) NOT NULL
    );
    PROMPT Creating table PROPOSER
CREATE TABLE PROPOSERS(
    applicant_id int generated by default on null as identity,
    first_name VARCHAR(70 CHAR) not null,
    last_name VARCHAR(70 CHAR)not null,
    phone_number NUMBER(1,38),
    email VARCHAR(80 CHAR)NOT NULL,
    pass VARCHAR(80 CHAR)NOT NULL);