create table Offers(
    offer_id INTEGER GENERATED BY DEFAULT ON NULL AS identity ,
    publication_date TIMESTAMP,
    postuler_id INTEGER not NULL,
    offrer_id INTEGER not NULL,
    location_id INTEGER not NULL,
    job_id INTEGER not NULL,
    statut INTEGER not NULL
)