SET DEFINE OFF
PROMPT INSERTING INTO OFFERS
begin
INSERT INTO OFFERS(publication_date,proposer_id,applicant_id,location_id,sector_id,status) VALUES ('04/01/2022',4,14,'DOUL','JARDI','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('16/01/2022', 16, 29, 'DOUL', 'ELEC', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('30/01/2022', 1, 20, 'BAFF', 'CHAUF', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('04/02/2022', 25, 18, 'YAOU', 'ELEC', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('05/02/2022', 2, 1, 'DOUL', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('10/02/2022', 3, 3, 'YAOU', 'PEINT', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('12/02/2022', 10, 2,'BAND', 'SECUR', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('17/02/2022', 8, 15, 'YAOU', 'FROID', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('20/02/2022',15,14,'DOUL','JARDI','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('25/02/2022', 14, 22, 'MARO', 'JARDI', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('28/02/2022', 6, 42,'BAME', 'MENAG', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('02/03/2022', 9, 25,'DSCH', 'BABYS', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('07/03/2022', 20, 12, 'DSCH', 'CHAUF','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('12/03/2022', 8, 40, 'YAOU', 'JARDI','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('15/03/2022', 21, 27, 'KRIB', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('18/03/2022', 18, 30, 'DOUL', 'PEINT', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('21/03/2022', 7, 21, 'DOUL', 'ELEC', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('25/03/2022', 14, 23, 'MARO', 'CHAUF', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('28/03/2022', 13, 24, 'DOUL', 'PLOMB', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('31/03/2022', 5, 9, 'LIMB', 'DECOR', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('01/04/2022', 8, 37, 'YAOU', 'REPET','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('02/04/2022', 11, 13, 'MBOU', 'TAILL', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('07/04/2022', 1, 19, 'BAFF', 'ELEC', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('12/04/2022', 20, 35, 'DSCH', 'BABYS', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('16/04/2022', 11, 36, 'MBOU', 'PLOMB', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('19/04/2022', 8, 40, 'YAOU', 'JARDI','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('20/04/2022', 19, 30, 'DOUL', 'PEINT', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('22/04/2022', 15,33, 'LIMB', 'SECUR','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('27/04/2022', 14, 38, 'BAGA', 'SECUR','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('30/04/2022', 18, 41, 'DOUL', 'MACON','FERMER');
INSERT INTO OFFERS(publication_date,proposer_id,applicant_id,location_id,sector_id,status) VALUES ('02-04-2022',18,14,'DOUL','JARDI','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('05/04/2022', 16, 1, 'DOUL', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('08/04/2022', 2, 1, 'DOUL', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('14/04/2022', 25, 18, 'YAOU', 'ELEC', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('21/04/2022', 8, 37, 'YAOU', 'REPET','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('27/04/2022', 8, 40, 'YAOU', 'JARDI','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('30/04/2022', 17, 41, 'DOUL', 'MACON','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('05/05/2022', 19, 17, 'DOUL', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('30/05/2022', 22, 22, 'MARO', 'JARDI', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('07/06/2022', 20, 12, 'DSCH', 'CHAUF','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('10/06/2022', 23, 37, 'YAOU', 'REPET','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('25/06/2022',21, 28, 'KRIB', 'DECOR','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('27/06/2022', 25, 12, 'DSCH', 'CHAUF','FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('30/06/2022', 22, 22, 'MARO', 'JARDI', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('02/07/2022', 24, 14, 'DOUL', 'JARDI', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('05/07/2022', 10, 26, 'BAND', 'TAILL', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('15/07/2022', 5, 31, 'DOUL', 'REPET', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('18/07/2022', 1, 6, 'LIMB', 'DECOR', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('20/07/2022', 16, 5, 'DOUL', 'MENAG', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('10/08/2022', 10,4, 'KRIB', 'BABYS', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('10/08/2022', 8, 10, 'YAOU', 'MENAG', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('12/08/2022', 17, 27, 'KRIB', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('25/08/2022', 11, 36, 'MBOU', 'PLOMB', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('05/09/2022', 19, 17, 'DOUL', 'SERVE', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('10/09/2022', 16, 5, 'DOUL', 'MENAG', 'FERMER');
INSERT INTO OFFERS(publication_date,proposer_id,applicant_id,location_id,sector_id,status) VALUES ('14/09/2022',4,NULL,'DOUL','JARDI','OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('30/09/2022', 1, NULL, 'BAFF', 'MACON','OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('05/10/2022', 19, NULL, 'DOUL', 'SERVE', 'OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('11/10/2022', 8, NULL, 'YAOU', 'REPET','OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('12/10/2022', 20, NULL, 'DSCH', 'BABYS','OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('15/10/2022', 1, NULL, 'BAFF', 'CHAUF','OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('18/10/2022', 16, 5, 'DOUL', 'MENAG', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('21/10/2022', 17, NULL, 'DOUL', 'MACON','OUVERTE');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('25/10/2022', 8, 18, 'YAOU', 'ELEC', 'FERMER');
INSERT INTO OFFERS(publication_date, proposer_id, applicant_id, location_id, sector_id, status) VALUES ('27/10/2022', 21, NULL, 'KRIB', 'SERVE', 'FERMER');
end;