PROMPT INSERTING IN PUBLICATION
SET DEFINE OFF
begin
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (1,TO_DATE('01-01-2022','DD-MM-YYYY'),50000,TO_DATE('18-01-2022','DD-MM-YYYY'), '03 mois','FERMER','Recherche dun employe qui sera present 3 fois la semaine',1);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (2,TO_DATE('03-01-2022','DD-MM-YYYY'),9000, TO_DATE('01-01-2022','DD-MM-YYYY'), '1 jour','FERMER','Qui seras diposnible pour une soirée et gardera les enfants',5);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (3,TO_DATE('05-02-2022','DD-MM-YYYY'),5000, TO_DATE('01-01-2022','DD-MM-YYYY'), '3jours','FERMER','Recherche dun employe qui sera present pendant 3jour pour veillez a la secutiter',10);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (4,TO_DATE('17-02-2022','DD-MM-YYYY'),30000,TO_DATE('01-01-2022','DD-MM-YYYY'), 'CDI','FERMER','Recherche dune couturiere pour la condection de pagne',16);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (5,TO_DATE('23-03-2022','DD-MM-YYYY'),15000, TO_DATE('01-01-2022','DD-MM-YYYY'),'CDI','FERMER','Rechere dun techincien pour reparation de fenetre ',14);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (6,TO_DATE('11-03-2022','DD-MM-YYYY'),15000, TO_DATE('01-01-2022','DD-MM-YYYY'),'02 ans','FERMER','Recherche dune menagere pour la prepopeter 3fois/semaine',29);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (7,TO_DATE('05-04-2022','DD-MM-YYYY'),17000, TO_DATE('01-01-2022','DD-MM-YYYY'),'03 mois','FERMER','Besion dune domestique pour gerer le menage 4foisemain pendant les vacances',15);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (8,TO_DATE('16-04-2022','DD-MM-YYYY'),11000, TO_DATE('01-01-2022','DD-MM-YYYY'), 'CDI','FERMER','Besion dun electricien pour linstallation electricte dans un batiment R2',18);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (9,TO_DATE('19-05-2022','DD-MM-YYYY'),8000, TO_DATE('01-01-2022','DD-MM-YYYY'), '01 jour','FERMER','Besion dun techinicien pour le diagnostique de banne dun frigot LG',19);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (10,TO_DATE('05-05-2022','DD-MM-YYYY'),7000, TO_DATE('01-01-2022','DD-MM-YYYY'),'CDI','FERMER','Besion dun maçon pour gerer un chantier',7);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (11,TO_DATE('16-06-2022','DD-MM-YYYY'),15000, TO_DATE('01-01-2022','DD-MM-YYYY'), '1 jours','FERMER','Besion dun cuisinier pour une soirée complete',20);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (12,TO_DATE('19-06-2022','DD-MM-YYYY'),8000, TO_DATE('01-01-2022','DD-MM-YYYY'), '09 MOIS','FERMER','Besion dune domestique pour lavée de linge chaque samedi durant lanee scolaire',26);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (13,TO_DATE('05-07-2022','DD-MM-YYYY'),7500, TO_DATE('01-01-2022','DD-MM-YYYY'),'03 mois','FERMER','Recherche dun repetiteur pour les vacances',23);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (14,TO_DATE('16-07-2022','DD-MM-YYYY'),11000, TO_DATE('01-01-2022','DD-MM-YYYY'), 'CDI','FERMER','Besion dun electricien pour linstallation electricte dans un batiment R2',18);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (15,TO_DATE('19-08-2022','DD-MM-YYYY'),10000, TO_DATE('01-01-2022','DD-MM-YYYY'), '1 ans','FERMER','Besion dun jardinier pour entretenir les plante 2 fois par MOIS',6);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (16,TO_DATE('05-08-2022','DD-MM-YYYY'),30000, TO_DATE('01-01-2022','DD-MM-YYYY'),'09 mois','FERMER','Besion dune menager de 8h a 16h chaque jour durant lannes scolaire',4);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (17,TO_DATE('16-09-2022','DD-MM-YYYY'),12000, TO_DATE('01-01-2022','DD-MM-YYYY'), '4 mois','FERMER','Besion dun chauffeur tourism pour a temps plein',24);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (18,TO_DATE('19-09-2022','DD-MM-YYYY'),8000, TO_DATE('01-01-2022','DD-MM-YYYY'), '01 jour','FERMER','Besion dun techinicien pour le diagnostique de panne dun climatiseur',19);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (19,TO_DATE('11-10-2022','DD-MM-YYYY'),23000, TO_DATE('29-10-2022','DD-MM-YYYY'), '01 jour','FERMER','Besion dun designer pour le décor dune maison a lavénement dhaloween',13);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (20,TO_DATE('20-10-2022','DD-MM-YYYY'),8000, TO_DATE('01-01-2022','DD-MM-YYYY'), 'CDI','LIBRE','Besion dun plombier pour linstallation dun forage',8);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (21,TO_DATE('03-11-2022','DD-MM-YYYY'),5000, TO_DATE('20-12-2022','DD-MM-YYYY'), 'CDI','LIBRE','Besion dun desinfecteur pour les congée de noEl',21);
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (22,TO_DATE('13-11-2022','DD-MM-YYYY'),8000, TO_DATE('01-01-2022','DD-MM-YYYY'), '01 jour','LIBRE','Besion dun designer pour le décor dune maison a lavénement de noel',13);
  end;  
  /