PROMPT INSERTING IN PUBLICATION
SET DEFINE OFF
begin
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (1,TO_DATE('01-01-2022','DD-MM-YYYY'),50000, TO_DATE('18-01-2022','DD-MM-YYYY'), '03 mois','FERMER',"Recherche d'un employe qui sera present 3 fois la semaine",1)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (2,TO_DATE('03-01-2022','DD-MM-YYYY'),15000,TO_DATE('01-01-2022','DD-MM-YYYY'), '1 an','OUVERT',"Recherche d'un employe qui sera present 3 a 4 fois la semaine, et n'habitant pas loin du quartier",2)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (3,TO_DATE('05-02-2022','DD-MM-YYYY'),30000,TO_DATE('01-01-2022','DD-MM-YYYY'), '2 semaines','OCCUPE',"Recherche d'un employe qui sera present 2 fois la semaine, transport assure",10)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (4,TO_DATE('17-02-2022','DD-MM-YYYY'),37600,TO_DATE('01-01-2022','DD-MM-YYYY'), 'CDI','OCCUPE',"Recherche d'un employe qui sera present tous les jours, hebergement gratuit",16)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (5,TO_DATE('23-03-2022','DD-MM-YYYY'),3000, TO_DATE('01-01-2022','DD-MM-YYYY'), '3 semaines','LIBRE',"Recherche d'un employe qui sera present tous les soirs entre 21h et 05h",14)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (6,TO_DATE('11-03-2022','DD-MM-YYYY'),5000, TO_DATE('01-01-2022','DD-MM-YYYY'), '02 ans','OUVERT',"Recherche d'un employe qui sera present de lundi a samedi entre 7h30 et 18h, qui saura préparee",29)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (7,TO_DATE('05-04-2022','DD-MM-YYYY'),2000, TO_DATE('01-01-2022','DD-MM-YYYY'), '06 mois','OUVERT',"Recherche d'un employe qui sera present tous les jours entre 7h30 et 12h",15)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (8,TO_DATE('16-04-2022','DD-MM-YYYY'),2000, TO_DATE('01-01-2022','DD-MM-YYYY'), '03 mos','LIBRE',"Recherche d'un employe qui sera present 3 a 4 fois la semaine",18)
  insert into PUBLICATIONS (publication_id, publication_date, salaire, death_line, duree, statut, description, besoin_id) values (9,TO_DATE('19-05-2022','DD-MM-YYYY'),2000, TO_DATE('01-01-2022','DD-MM-YYYY'), '06 mois','LIBRE',"Recherche d'un employe qui sera present 3 a 4 fois la semaine",19)
end;