
PROMPT INSERTING into recommendations
SET DEFINE OFF;
begin
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('KANTEU',691806088,'anangamax@gmail.com','il est tres bon','confirmer',1);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('KOUMEN',655447788,'koumen@gmail.com','il est tres bon et courageux','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('FAMI',655447777,'fami@gmail.com','il est bon et courageux','rejeter',3);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('LEYA',65548899,'leya@gmail.com','il est bon et courageux','confirmer',4);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('WANDJI',659332211,'wandji@gmail.com','courageux','confirmer',5);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('CHEMO',654556633,'chemo@gmail.com','propre','rejeter',5);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('BAVOUA',677382211,'bavoua@gmail.com','alcolique','rejeter',5);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('EBONKE',659334611,'ebonke@gmail.com','alcolique','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('POKEM',659334211,'pokem@gmail.com','courageux','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('POUANI',659132211,'pouani@gmail.com','travailleur','confirmer',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('RAYE',659232211,'raye@gmail.com','courageux','rejeter',6);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('SADO',659333211,'sado@gmail.com','il est tres  courageux','confirmer',6);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('SAMI',669332211,'sami@gmail.com','il est tres  courageux','confirmer',7);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('SANGUO',656332211,'sanguo@gmail.com','il est tres  courageux','rejeter',7);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('SIANOU',659432211,'sianou@gmail.com','respectueux','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('SIBEU',659338821,'sibeu@gmail.com','il est tres  courageux','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('SILHA',759332211,'silha@gmail.com','il est tres  courageux','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('TANKO',859332211,'tanko@gmail.com','il est tres  courageux','rejeter',3);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('TCHAGOU',959332211,'tchagou@gmail.com','il est tres  courageux','confirmer',3);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('DJOUDA',659332213,'djouda@gmail.com','travailleur','confirmer',8);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('FOSSA%',659332214,'fossa@gmail.com','il est tres  courageux','confirmer',9);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('JIDJOU',659332215,'jidjou@gmail.com','travailleur','rejeter',10);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('JOSOUE',659332216,'josue@gmail.com','il est tres  courageux','rejeter',11);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('KANGUE',659332217,'kangue@gmail.com','il est tres  courageux','rejeter',11);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('KENE',659332219,'kene@gmail.com','propre','confirmer',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('KENCHOUN',659332231,'kenchoun@gmail.com','competant','rejeter',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('KENGNI',659332241,'kengni@gmail.com','pas competant','rejeter',3);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('LONTSI',659332251,'lontsi@gmail.com','il est tres  courageux','rejeter',1);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('MAKOLO',659332261,'makolo@gmail.com','il est tres  courageux','rejeter',1);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('MALONJU',659332271,'malonju@gmail.com','manque de concentration','rejeter',12);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('MANGA',659332281,'manga@gmail.com','il est tres  courageux','confirmer',12);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('MBAH',659332291,'mbah@gmail.com','il est tres  courageux','rejeter',13);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('MOTSO',659331211,'motso@gmail.com','courageux','confirmer',14);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('MOUOFO',657334211,'wanji@gmail.com','courageux','confirmer',15);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NA',659335211,'na@gmail.com','il est tres insolant','rejeter',12);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NGEUNOU',659337211,'ngeunou@gmail.com','courageux','confirmer',12);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NGUIAKAM',659338211,'nguiakam@gmail.com','courageux','rejeter',33);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NIKILEDJI',659339201,'nikiledji@gmail.com','distrait','confirmer',20);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NJAHA',659330201,'njaha@gmail.com','il  manque de qualite','rejeter',22);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NONO',650332201,'nono@gmail.com','courageux','rejeter',32);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('ZOMO',651332201,'zomo@gmail.com','courageux','rejeter',15);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('PEUGHOUIA',652332201,'peughouia@gmail.com','courageux','confirmer',5);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('NTANGUEN',653332201,'ntanguen@gmail.com','courageux','confirmer',9);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('DJEJO',654332201,'djejo@gmail.com','meprisant','confirmer',2);
INSERT INTO recommendations(recom_nom,recom_numero,recom_email,recom_contenue,recom_statut,user_id) VALUES('FOKOU',655332201,'fokou@gmail.com','il est souple','confirmer',9);
end;
/